codecov:
  token: d82f05a9-b111-4f1d-bcb4-02c257757ec4
coverage:
  status:
    project:
      d1:
        target: auto
        flags:
          - d1
      d2:
        target: auto
        flags:
          - d2
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: yes
  require_head: yes
  branches: null
flags:
  d1:
    paths:
      - d1/coverage.txt
    carryforward: true
  d2:
    paths:
      - d2/coverage.txt
    carryforward: true
